### ISSUE TITLE
Remove the language in ``` markdown? 

### ISSUE THREAD

**Issue by NovaEmiya** [NovaEmiya/ShittyBotty#1]
Currently in ctx.reply of _run command we are using code block markdown, because there are many languages supported for this command, shall we just remove the syntax highlighting, making it just the backticks...? This will remove all the syntax highlighting tho 🤔 @Nimboss2411

**Comment by Nimboss2411** [comment]
Yea because there are many languages it's actually good to specify no one language and just make it a languageless codeblock, ill remove the syntax highlighting
